### ISSUE TITLE
Need a way to sign the chart before publish

### ISSUE THREAD

**Issue by alita1991** [nflaig/semantic-release-helm#11]
Hi,

I have a use case where I must sign the helm chart before publishing it to the registry. By exploring the code, I notice there is no way to send the extra configuration to the helm package action.

Code snippet:
`await execa(
                'helm',
                ['package', configPath]
            );`

Helm command:
`helm package --sign ./mychart --key mykey --keyring ~/.gnupg/secring.gpg`

Is there any way to achieve that or a plan to introduce this feature?

Thanks

**Comment by nflaig** [comment]
Hey @alita1991,

sounds like a something that could be added and enabled via a feature flag.

I might find time to look into it over the weekend but can't guarantee that.

If you need that feature urgently, feel free to look into yourself and open a PR, I am happy to review it and create another release of the package.

**Comment by alita1991** [comment]
Hi @nflaig,

I added  the `oci://` prefix, because of the following error:

`Error: scheme prefix missing from remote (e.g. "oci://")`

I'm using the latest version of helm 3.11.2.
