### ISSUE TITLE
allow for extra args on helm push?

### ISSUE THREAD

**Issue by manuschillerdev** [nflaig/semantic-release-helm#15]
for pushing to private nexus registries one has to specify the flag `--context-path=/repo/chart` with the `helm cm-push` command.

It would be awesome if we could specify additional parameters for `helm cm-push` via the options :)

**Comment by nflaig** [comment]
Should be quite simple to implement at this point, similar to
- https://github.com/nflaig/semantic-release-helm/pull/12

Feel free to open a PR if you need this quickly
