### ISSUE TITLE
Support for Azure container Registry

### ISSUE THREAD

**Issue by nishaero** [nflaig/semantic-release-helm#17]
Is there support for ACR, as i see there is support for AWS S3 but for OCI based registries, the option is not provided. 

Can you guide me where the changes should occur, just like its done for S3

**Comment by nflaig** [comment]
Haven't used ACR but if it supports OCI it will work, this is the default protocol if you don't specify any other options
https://github.com/nflaig/semantic-release-helm/blob/ae5ed181b59933e292b9eb36a03ed3a1d6540869/lib/publish.js#L81-L83

Based on [their docs](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-intro) seems like it

![image](https://github.com/nflaig/semantic-release-helm/assets/38436224/c895d90a-624b-4810-b2a2-62e070f0c861)

**Comment by nishaero** [comment]
Yes, i saw that it already supports oci and will try that. thank you!

Will update here if it worked.. or will create a PR if necessary.

**Comment by nishaero** [comment]
seems like helm could not login to acr registry. i get the following error. 
It works when i execute helm registry login directly on the ci file but not when using the semantic release 

`[9:43:11 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: helm registry login --username robot$xxx-platform+helm-ci --password-stdin oci:
time="2023-06-26T09:43:11Z" level=info msg="Error logging in to endpoint, trying next endpoint" error="Get \"https://oci/v2/\": dial tcp: lookup oci on xx.xx.0.12: server misbehaving"
Error: Get "https://oci/v2/": dial tcp: lookup oci on xx.xx.0.12:53: server misbehaving`

Should'nt this code here split the oci from the  repo uri that starts with oci://acrregistry.azurecr.io/repo/

https://github.com/nflaig/semantic-release-helm/blob/ae5ed181b59933e292b9eb36a03ed3a1d6540869/lib/verifyConditions.js#L14C4-L20

**Comment by nishaero** [comment]
this is the url im setting oci://acr001.azurecr.io/chart-helm/

**Comment by nflaig** [comment]
This would be the resulting login url

```
> "oci://acr001.azurecr.io/chart-helm/".replace("oci://", "").split('/')[0]
'acr001.azurecr.io'
```

Not sure where the `https://` prefix is coming from, this is not added by the module.

**Comment by nishaero** [comment]
ya.. im not sure if its being done in the ci cd repo in gitlab.. somewhere i think its appending the https because its by default always registers with harbor,, maybe i need to look deeper

**Comment by nflaig** [comment]
Are you using the latest versio (v2.6.0) of the module?

There was an issue with oci prefix but that was fixed a while ago
- https://github.com/nflaig/semantic-release-helm/pull/14

Also helm is known to introduce breaking changes in minor releases, it hard to keep this module compatible. My recommendation is to only upgrade to a newer helm version if it is really required.

**Comment by nishaero** [comment]
I'm not sure, I have to check where this release version is set, after the update i created the new release version (v2.10.0) which should include this change you mentioned..

**Comment by nflaig** [comment]
> I'm not sure, I have to check where this release version is set

package.json

**Comment by nishaero** [comment]
so, to update the lock file, what should be done ? im new to npm here.

**Comment by nflaig** [comment]
just update the version in package.json and run `npm install`

**Comment by nishaero** [comment]
Yes, updated that.. but still get the same error that its trying to use the https://.. im not sure where this is coming from.

`2:36:39 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: helm registry login --username robot$hypertrust-platform+helm-ci --password-stdin acr001.azurecr.io
Error: Get "https://acr001.azurecr.io/v2/": unauthorized: aad access token with sp failed client id must be guid`

**Comment by nflaig** [comment]
> not sure where this is coming from

Likely helm doing that, as mentioned above, they introduce breaking changes like this even in minor versions. This module is mostly tested with 3.10 and below, can't tell if it works with high versions without any changes.

**Comment by nishaero** [comment]
the issue is fixed. you are correct, gitlab was passing the registry creds from the global env variables and the precedence was not working.. exposting them worked. Thank You!
