### ISSUE TITLE
Chart.yaml version doesn't get updated

### ISSUE THREAD

**Issue by Piwero** [nflaig/semantic-release-helm#31]
For some reason when I create a new release, the version from Chart.yaml doesn't get updated on this repo. https://github.com/Piwero/piwhelm/blob/main/charts/piwhelm/Chart.yaml
Is there any setup missing?
Thanks

**Comment by nflaig** [comment]
Possibly related to https://github.com/semantic-release/semantic-release/issues/1593

**Comment by never00rei** [comment]
@Piwero how did you fix this in the end if you ever did? I'm experiencing the same issue.
