### ISSUE TITLE
multiple charts in the /charts folder

### ISSUE THREAD

**Issue by dmitry-mightydevops** [nflaig/semantic-release-helm#7]
Hi @nflaig 

Is it possible to have different chart versions for each chart?

i.e.
charts/
  ch1
  ch2
  ch3

current tag is 1.0.0, and charts/{cj1, ch2, ch3}/Chart.yaml has version: 1.0.0
I modify ch1 and it gets 1.0.1
I modify ch2 and it gets 1.0.1 as well

My current understanding is that it is impossible, means that in my second modifications ch2/Chart.yaml would get 1.0.2
means ch2 will have just two releases: 1.0.0 and 1.0.2, i.e. 1.0.1 would be missed

Do I get it right or miss something?

Thanks,
Dmitry

**Comment by nflaig** [comment]
Hey @dmitry-mightydevops 👋 

this is inherently an issue with semantic-release rather as it by default just work with single component repos. If you have a monorepo with multiple components with different version which should be released and versioned separately then you might want to look into something like [https://github.com/pmowrer/semantic-release-monorepo](https://github.com/pmowrer/semantic-release-monorepo).

Alternative solution is to have a separate CI job per chart which executes in the context of the chart. In that case you will have to add some scoping to your commits as well so only the commits which modified the specific chart are considered.

I hope that helps, let me know if you need further input or if I misunderstood something.

**Comment by dmitry-mightydevops** [comment]
thank you nflaig!
